name: Best Workflow Ever 
on:
  push:
    branches:
      - pipe

jobs:
  test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Run The Tests  
        run: npm test

  build_Run:
      runs-on: ubuntu-latest
      needs: test
      steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Run The Tests and Run The App 
        run: |
          npm install --production &
          npm start &
      - name: Curl the App
        run: curl http://localhost:3000
        