name: Best Workflow Ever
on:
  push:
    branches:
      - pipe

jobs:
  test_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 18

      - name: Run Tests
        run: npm test

      - name: Install Dependencies
        run: npm install

      - name: Start App & Curl
        run: |
          npm start &
          sleep 5
          curl http://localhost:3000
